# Note: Remove the baseurl in order to deploy at the domain root
title: Sacbe García
# Whether the header (with large title and subtitle) should be displayed
header: false
subtitle: Proyectos realizados de ciencia de datos
author: Sacbe García
description: Proyectos de ciencia de datos 
show_author: true
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
# permalink: /blog/:categories/:year/:month/:day/:title.html
permalink: /blog/:categories/:slug
timezone: America/mexico_city
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
plugins:
  - jekyll-feed
